### ISSUE TITLE
regG(): X.test is not a function

### ISSUE THREAD

**Issue by floppa-the-flopper** [Chasyxx/EnBeat_NEW#4]
![image](https://github.com/Chasyxx/EnBeat_NEW/assets/142877833/63de2f09-66c3-499f-9c6b-4161772527c5)

**Comment by Chasyxx** [comment]
the 2nd input should be a regular expression. maybe i should have had the function say that, but this is not a problem

**Comment by floppa-the-flopper** [comment]
https://chasyxx.github.io/EnBeat_NEW/#EnBeat2-q1ZKzk9JVbJSKoqwra7VKYrQK0ktLrHV0LS10yjRUjc0MjZRj9YoUSuxszM00lQtidXUKUpNd9coASrVVKoFAA i think i got it by defining 1 variable and 1 function
